version: "3"
services:

  go-cqhttp:
    build: ./go-cqhttp
    image: tarabot/go-cqhttp
    volumes:
      - "./go-cqhttp-data:/data"
    environment:
      - TZ=Asia/Shanghai
    networks:
      - internal_net
    expose:
      - 5700
    ports:
      - 9999:9999
    depends_on:
      - tarabot

  tarabot:
    build: ./tarabot
    image: tarabot/tarabot
    environment:
      - TZ=Asia/Shanghai
    networks:
      - internal_net
    expose:
      - 8080
    volumes:
      - "./tarabot:/root/tarabot"

networks:
  internal_net: